[workspace]

members = ["crates/*"]

[workspace.dependencies]
ahash = "0.8.0"
arrow = "20.0.0"
arrow-flight = "20.0.0"
async-trait = "0.1.52"
atoi = "1.0.0"
atomic = "0.5.1"
atomic_float = "0.1.0"
byte-slice-cast = "1.2.1"
clap = { version = "4.0", features = ["derive"] }
criterion = { version = "0.3.5", features = ["html_reports"] }
delegate = "0.7.0"
env_logger = "0.9.0"
fast-float = "0.2.0"
float-ord = "0.3.2"
futures = "0.3.21"
fxhash = "0.2.1"
gdl = "0.2.6"
itertools = "0.10.3"
linereader = "0.4.0"
log = "0.4.14"
memmap2 = "0.5.3"
nanorand = "0.7.0"
num = "0.4.0"
num_cpus = "1.13.1"
num-format = "0.4.0"
numpy = "0.16.0"
page_size = "0.4.2"
parking_lot = "0.12.0"
pico-args = "0.5.0"
pyo3 = "0.16.0"
pyo3-log = "0.6.0"
rand = "0.8.5"
rayon = "1.5.1"
serde_json = "1.0.79"
serde = { version = "1.0.136", features = ["derive"] }
tempfile = "3.3.0"
thiserror = "1.0.30"
tokio = "1.17.0"
tonic = "0.8.0"
